---
apiVersion: v1
kind: Secret
metadata:
  name: tweeter-secret
  labels:
    app: tweeter
  namespace: myns
type: Opaque
data:
  BUCKET_ACCESS_KEY: RE8wMEwzNkJGUlRZRkhNUURSNDQ=
  BUCKET_SECRET_KEY: TUtUcFJtS092V1FpSVFHWWhPRVBWTXovWVFqSlhZbGFhNzQ2N2lYeC9tRQ==
  JWT_SECRET_KEY: and0c2VjcmV0
  SPRING_DATASOURCE_PASSWORD: QVZOU19vM0ZxeThuQmRfUkVPa3dJWXFs
  SPRING_MAIL_PASSWORD: eXRjZWlidnR6Z3pjbHZwZA==