name: Deploy to Heroku
on:
  push:
    branches:
      - release
jobs:
  deploy heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.heroku.api.key }}
          heroku_app_name: "tweeter"
          heroku_email: ${{ secrets.heroku.email }}
          appdir: "backend"